### ISSUE TITLE
dfs_lfs.c->_dfs_lfs_write() cannot accurately update the file size

### ISSUE THREAD

**Issue by dasg-wf** [mysterywolf/littlefs#11]
```
static int _dfs_lfs_write(struct dfs_fd* file, const void* buf, size_t len)
{
    lfs_ssize_t ssize;
    dfs_lfs_fd_t* dfs_lfs_fd;
    RT_ASSERT(file != RT_NULL);
    RT_ASSERT(file->data != RT_NULL);

    if (file->type == FT_DIRECTORY)
    {
        return -EISDIR;
    }

    dfs_lfs_fd = (dfs_lfs_fd_t*)file->data;

    ssize = lfs_file_write(dfs_lfs_fd->lfs, &dfs_lfs_fd->u.file, buf, len);
    if (ssize < 0)
    {
        return _lfs_result_to_dfs(ssize);
    }

    /* update position and file size */
    file->pos = dfs_lfs_fd->u.file.pos;
    file->size = dfs_lfs_fd->u.file.ctz.size;

    return ssize;
}
```
In function `_dfs_lfs_write()`, the value `dfs_lfs_fd->u.file.ctz.size` in `lfs_file_write()` will not be updated, it will only be updated actually after calling flush. Therefore, the value of `file->size` will not be updated. This is an error. This may cause problems in other places where you directly access `file->size` to obtain the file length.

**Comment by kurisaW** [comment]
Users should not care about the interface layer if they do application development. You can use the read() or stat() functions to get the file size, and when I tried to step it, I found that `dfs_lfs_fd-> u.fly.ct.size` was not unupdated, but kept the last file size. If you try to write to the file a second time to increase the file size, and then read it again, you will find that `dfs_lfs_fd-> u.fly.ct.size` has been updated to the previous file size

![d56d801d1720e05afa49f4611b0be9e](https://github.com/RT-Thread-packages/littlefs/assets/98592772/0730664c-7623-4d8e-9234-a3a7a7907fc0)
