### ISSUE TITLE
适配rtt-v5.2.0

### ISSUE THREAD

**Issue by shishirong** [mysterywolf/littlefs#17]
_dfs_lfs_mkfs,_dfs_lfs_read,_dfs_lfs_write,_dfs_lfs_lseek几个函数的原型与struct dfs_file_ops中的类型不兼容.
另外建议从上游合并一下更新

**Comment by Rbb666** [comment]
已修复： https://github.com/RT-Thread-packages/littlefs/pull/20

**Comment by wdfk-prog** [comment]
已拉取上游更新: https://github.com/RT-Thread-packages/littlefs/pull/21

**Comment by Rbb666** [comment]
@mysterywolf 满老师，此issue可以关闭了
