### ISSUE TITLE
Add the rtconfig.h header file inclusion to lfs.h

### ISSUE THREAD

**Issue by Ghost-Girls** [mysterywolf/littlefs#22]
The lfs_config structure lacks the inclusion of the rtconfig.h header file, resulting in missing pointer members in the structure and causing a mount failure.

**Comment by mysterywolf** [comment]
we just sync and merge the latest upstream release version. Could you try again? If it still doesn't work, could you submit a PR. Thank you

**Comment by wdfk-prog** [comment]
> The lfs_config structure lacks the inclusion of the rtconfig.h header file, resulting in missing pointer members in the structure and causing a mount failure.lfs_config结构中没有包含rtlib. h头文件，导致该结构中缺少指针成员并导致装载失败。

- The header includes rtthread.h, so it's not relevant to this package; Check your project code to see if rtlib.h works. Also I didn't find the rtlib.h header in the latest RTT code.

https://github.com/RT-Thread-packages/littlefs/blob/07386a9283f69a55243acdea67b52884d74e5bc5/lfs_config.h#L4C1-L4C22
